styled-components/babel-plugin-styled-components

src/index.js, src/utils/get-target.js, test/fixtures/add-display-names/after.js, test/fixtures/add-display-names/before.js, test/fixtures/add-identifier-and-display-name/after.js, test/fixtures/add-identifier/after.js
With the new private API, all the IIFEs are unnecessary since we can just pass an object to the styled() calls. This commit updates the plugin and the tests to reflect the new result. Need to wait for styled-components/styled-components#227 (which introduces the new API) to be merged before releasing.
----
Please review the code @vdanchenkov, I'm not very familiar with writing babel plugins, so if you see things that could be done easier please let me know!
@geelen please review the result of the conversion in the `after.js` files of the fixtures!
=> Rewrite to the new, private API

src/index.js
This breaks currently:
```JS
import styled from 'styled-components'
export default styled.div``
```
Now #8 will fix this specific case, but I think we should guard against some undefined cases anyway.
=> Fix undefined displayName

src/utils/detectors.js, src/visitors/transpileTemplateLiterals.js, test/fixtures/13-allow-chains-of-member-calls/.babelrc, test/fixtures/13-allow-chains-of-member-calls/after.js, test/fixtures/13-allow-chains-of-member-calls/before.js
This change loosens checks to detect 
```
styled.div.attrs().anotherCall()`width: 100%;`
``` 
as styled component. I think it's a good change anyway, but besides that it allows syntax proposed in 
styled-components/styled-components#365.
=> Allow chains of member calls

README.md, src/utils/options.js, test/fixtures/02-add-identifier/.babelrc, test/fixtures/02-add-identifier/.babelrc.orig, test/fixtures/03-add-identifier-and-display-name/.babelrc, test/fixtures/03-add-identifier-and-display-name/.babelrc.orig, test/fixtures/04-track-the-imported-variable/.babelrc, test/fixtures/04-track-the-imported-variable/.babelrc.orig, test/fixtures/05-use-file-name/.babelrc, test/fixtures/05-use-file-name/.babelrc.orig, test/fixtures/06-work-with-hoisted-default-as-import/.babelrc, test/fixtures/06-work-with-hoisted-default-as-import/.babelrc.orig, test/fixtures/14-preprocess-css/.babelrc, test/fixtures/15-preprocess-keyframes/.babelrc, test/fixtures/16-preprocess-import/.babelrc, test/fixtures/17-no-preprocess-import/.babelrc
Given our amazing ability to improve the debugging experience and to minify the styles, a lot of people who aren't server-side rendering will want to use this plugin, so I think it makes sense to disable SSR by default.
=> Disable SSR option by default

README.md, src/css/placeholderUtils.js, src/minify/index.js, src/visitors/minify.js, test/fixtures/08-minify-css-to-use-with-transpilation/after.js, test/fixtures/09-minify-css-to-use-without-transpilation/after.js, test/fixtures/09-minify-css-to-use-without-transpilation/before.js, test/minify/index.test.js
Fixes: https://github.com/styled-components/styled-components/issues/888
The new logic works like this:
- Joins quasis with placeholders
- Removes multi-line comments
- Splits by newlines
- Removes line-comments
- Filters lines with only line-comments
- Joins
This thus removes all comments and gives us greater
granularity for minification, since it's only a single
string we now operate on. This should prevent mangling
in the future.
=> Strip comments properly from styled template strings

package.json, src/css/preprocessUtils.js, yarn.lock
This prevents bugs with shared options and middleware when different
babel plugins use stylis.
cc @thysultan
=> Upgrade to stylis 3.2 and use constructor

src/visitors/displayNameAndId.js
Fixes #80
It removes invalid characters from the display name so it can be used as a valid classname.
=> Sanitize display name to prevent invalid class names

src/visitors/displayNameAndId.js
https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors
=> Use file.opts.filename instead of file.opts.basename for babel 7 compatibility

package.json, yarn.lock
Hi, I wanted to tackle one of the issues here, but I'm developing on Windows and here's what I get:
```
> rm -rf lib
'rm' is not recognized as an internal or external command,
operable program or batch file.
```
Replacing `rm -rf` with `rimraf` solves the problem.
=> Use rimraf for cross-platform "rm -rf"

src/visitors/displayNameAndId.js
As described in #79, `String.prototype.replace` needs at least a `RegExp` with the `global` flag to replace all occurrences of a text in the source text.
This concrete example was causing the tests to fail on Windows (only the first backslash was replaced with a slash).
=> Use RegExp instead of a string in String.prototype.replace

src/utils/detectors.js, test/fixtures/19-transpile-require-default/after.js
Adds path traversal logic unceremoniously cribbed from lodash/babel-plugin-lodash#194 to replace the built-in import tracking that was removed in Babel v7.0.0-beta.3.
=> Support Babel v7.0.0-beta.3 (fixes #96).

src/minify/index.js, test/fixtures/18-preprocess-inject-global/after.js, test/fixtures/18-preprocess-inject-global/before.js, test/fixtures/19-transpile-require-default/after.js, test/minify/index.test.js, yarn.lock
Add an exception to preserve comments that begin with `/*!`
Related to https://github.com/styled-components/styled-components/issues/1249
=> Preserve comments that begin with "/*!"

src/utils/options.js, test/fixtures/20-annotate-styled-calls-with-uglify-pure-comments/.babelrc, test/fixtures/21-annotate-keyframes-with-uglify-pure-comments/.babelrc
unfortunately this feature seems to dramatically inflate the
amount of time babel takes to process files... perhaps there is
an unintended loop happening or something of the like
fixes #126
=> disable "uglifyPure" mode by default

package.json, src/index.js, src/visitors/desugarStyled.js, test/__snapshots__/index.test.js.snap, test/index.test.js, yarn.lock
This change allows us to drop the element whitelist in styled-components
v4 and automatically support any new element types that become
available over time.
Closes #125
=> desugar styled.tag to styled('tag')

src/visitors/transpileCssProp.js
I ran into an "Object.entries not a function" error when setting up `babel-plugin-styled-components` in node `6.12.2`.  Turns out [`Object.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Browser_compatibility) is only supported in node `7.0.0+`. Even though this project's `babelrc` [targets node `4`](https://github.com/styled-components/babel-plugin-styled-components/blob/master/.babelrc#L6-L8), it is not setup to polyfill methods like `Object.entries`. Luckily, `Object.entries` is only used once. I think the easiest solution is to replace the single use of `Object.entries` with a call to `Object.keys` instead.
=> Replace Object.entries with Object.keys for better node compatibility

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js, test/fixtures/transpile-css-prop/code.js, test/fixtures/transpile-css-prop/output.js
Reduced version of #228 since the injection location code isn't totally ready yet
1. fix transpilation of objects being passed into the css prop
2. modifications from @bpierre to support custom elements, lowercase component variable names with dots, nested component names with dots
=> fix object syntax css prop, support more types of components & custom elements

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-add-import/output.js, test/fixtures/transpile-css-prop-add-require/output.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js, test/fixtures/transpile-css-prop/code.js, test/fixtures/transpile-css-prop/output.js
inject the generated components before the tree they're being used in rather than to the end of the file, this fixes situations where a bundler might wrap a component in an IIFE and our component generated from the css prop hasn't been initialized yet (fixes #221, #203)
=> fix injection location of generated components via css prop

src/visitors/transpileCssProp.js
Apparently `importName` can have many different types:
https://github.com/styled-components/babel-plugin-styled-components/issues/232#issuecomment-507223968
This commit ensures that the check whether the name is in the scope
(bindings) does not break on plain strings.
Closes: #232
=> Fix `importName` type confusion (string, bool, node)

src/utils/detectors.js
=> Fix early return for cached `false` values in `importLocalName`

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js
**Background**
Spread operator does not work. See the following issue for more details: https://github.com/styled-components/babel-plugin-styled-components/issues/235.
This fails as the transpiler tries to convert the SpreadElement node into a key/value. Additionally, it needs to ensure that objects are converted into a p
**Change**
* Do not treat spreadElement as an expression
* Properly map object values of the SpreadElement argument into Styled component props.
**Test Plan**
Added a new test case that validates spread elements and nested spread elements are handled properly. The gen code looks correct, but I'm not too familiar with what styled components gen code should look like.
=> Support Spread Element

src/utils/options.js, src/visitors/displayNameAndId.js, test/fixtures/use-namespace/.babelrc, test/fixtures/use-namespace/code.js, test/fixtures/use-namespace/output.js
This is a fix of [2974](https://github.com/styled-components/styled-components/issues/2974).
I have already implemented fork of this repo and tested it with my adoption: 
[@rajzik/babel-plugin-styled-components](https://github.com/rajzik/babel-plugin-styled-components-namespace).
It is working well and it creates a unique name with the given namespace.
This will resolve all issues with micro frontends class name duplication.
=> Add namespace option

src/utils/detectors.js
In this discussion: https://github.com/styled-components/babel-plugin-styled-components/pull/234 that introduced the change to `cacheKey in localNameCache`, the author referenced a comment you made here:
https://github.com/styled-components/babel-plugin-styled-components/pull/230#discussion_r298018008
in which, you indicated that the `false` value there was to ensure that the traversal would continue again until you either picked up the import or dynamically injected it (I think?)
When the code was changed to account for this it failed to maintain the same behavior in the case that localName was intentionally left `false`.
This change ensures that the previous behavior (allowing the intentionally set `false` to fall through the cache lookup) remains, while ensuring a `false` value in the …
=> Ensure cache miss to fix ESM compiling

src/utils/detectors.js, src/utils/options.js, src/visitors/assignStyledRequired.js, test/fixtures/add-identifier-with-top-level-import-paths/.babelrc, test/fixtures/add-identifier-with-top-level-import-paths/code.js, test/fixtures/add-identifier-with-top-level-import-paths/output.js
Related to issue #287 
The main purpose is to be able to transform styled-components wrappers like [xstyled](https://github.com/smooth-code/xstyled).
PS: Couldn't install packages with node v12.17.0 and the repository `yarn.lock`. Hence the updated `yarn.lock`.
=> Add topLevelImportPaths option

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js
Using Spread syntax in css prop is currently supported, but this syntax is not supported.
```js
<div
css={{
...obj,
{ color: 'red' }
}}
>
hi
</div>
```
it causes the error that can not read property `reduce` because it has not `property.argument.properties`
This PR resolves it by recursing only when the argument of Spread Element is object expression.
=> Recurse only when the argument of Spread Element is object expression

src/utils/detectors.js, test/fixtures/add-identifier-with-top-level-import-paths-and-named-import/.babelrc, test/fixtures/add-identifier-with-top-level-import-paths-and-named-import/code.js, test/fixtures/add-identifier-with-top-level-import-paths-and-named-import/output.js
To support the upcoming `topLevelImportPaths` option, this allows this babel plugin to pick-up `styled` as a named export:
```js
import { styled } from '@wrapping/package'`
```
config:
```
[
'styled-components',
{
topLevelImportPaths: ['@wrapping/package'],
},
]
```
=> Support styled as a named export

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js
Sorry, there was a problem with the PR I created. (#301)
I noticed `cssObj ` needs to be injected via props.
https://github.com/styled-components/babel-plugin-styled-components/blob/2580a0597e383f7b49ec48c322ca6ac00ae19556/test/fixtures/transpile-css-prop-all-options-on/output.js#L283-L287
I tested it in my project in advance, but at that time I didn't notice that because webpack inserted the styles that were imported from another file.
I'll recreate the PR with some fixes.
=> Revert "Recurse only when the argument of Spread Element is object expression"

package.json, src/visitors/transpileCssProp.js, test/fixtures/transformed-imports-with-jsx-member-expressions/.babelrc, test/fixtures/transformed-imports-with-jsx-member-expressions/code.js, test/fixtures/transformed-imports-with-jsx-member-expressions/output.js
this makes sure that other babel transformations that rename variables will be able to process the ast nodes created by this plugin
fixes #240
=> preserve structure of JSX member expressions in generated ast nodes

src/utils/detectors.js, src/visitors/transpileCssProp.js
When using `rollup` to bundle, all versions after `1.10.5` fail to generate a `withConfig` for styled components.
Reported issue [here](https://github.com/styled-components/babel-plugin-styled-components/issues/280).
Changes between versions: https://github.com/styled-components/babel-plugin-styled-components/compare/v1.10.5...v1.10.6
The breaking (but correct) change in `v1.10.6`:
```typescript
if (!bypassCache && cacheKey in localNameCache) {
return localNameCache[cacheKey]
}
```
This change was necessary to utilize the cache and exit early:
```typescript
const localNameCache = {};
// First pass, cacheKey = 'first'
localNameCache[cacheKey]; // -> undefined
cacheKey in localNameCache; // -> false
// Second pass, cacheKey = 'first'
localNameCache[cacheKey]; // -> false
cacheKey in …
```
=> Resolve operability issue with rollup

.prettierrc, src/visitors/displayNameAndId.js, test/fixtures/add-identifier-and-display-name/code.js, test/fixtures/add-identifier-and-display-name/output.js
Resolves issue #322 where if you have an existing withConfig on your component in order to leverage shouldForwardProp babel was not adding a displayName or componentId
this takes the existing expression adds the additional args and replaces the existing withConfig
=> merge existing withConfig arguments to allow SSR when using shouldForwardProp

src/visitors/displayNameAndId.js, test/fixtures/add-identifier-with-top-level-import-paths-and-named-import/output.js, test/fixtures/annotate-styled-calls-with-pure-comments/output.js, test/fixtures/minify-single-line-comments-with-interpolations/output.js, test/fixtures/track-the-imported-variable/output.js
Currently, the sc- is added at the start of the hash by replacing the first digit. The problem is that the hash may also start by a letter, causing the class name to sometimes miss the sc- prefix.
This fix makes it possible to use this plugin with styled-components@5 + jest-styled-components@7.
In the meantime, I've published the fix on npm under [@chalbert/babel-plugin-styled-components](https://www.npmjs.com/package/@chalbert/babel-plugin-styled-components)
In my experience, it fixes the following issues :
#268
styled-components/jest-styled-components#297
styled-components/jest-styled-components#335
styled-components/jest-styled-components#294
And potentially others.
=> Ensure sc- prefix is always added

package.json, src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop-all-options-on/code.js, test/fixtures/transpile-css-prop-all-options-on/output.js, test/fixtures/transpile-css-prop/code.js, test/fixtures/transpile-css-prop/output.js
=> teach babel plugin about certain spread application scenarios with "css" prop

src/visitors/transpileCssProp.js, test/fixtures/transpile-css-prop/code.js, test/fixtures/transpile-css-prop/output.js
=> handle complex expressions inside CSS prop object syntax

src/utils/options.js, src/visitors/displayNameAndId.js, test/fixtures/use-directory-name/.babelrc, test/fixtures/use-directory-name/code.js, test/fixtures/use-directory-name/output.js
This PR adds a new option: `meaninglessFileNames`.
Consider the following use case:
- A developer enables `babel-plugin-styled-components` with the defaults of `displayName: true` and `fileName: true`.
- They organize their components with the following structure:
```
src/
components/
MyComponent/
index.js
styles.js
```
`styles.js` would be the file where they place their styled components.
- For consistency, they always use `Container` for the root element of every component:
```jsx
// index.js
import React from 'react';
import { Container } from './styles.js';
const MyComponent = () => <Container>Hello world!</Container>;
```
The class name generated for the `Container` element of `MyComponent` would be something like `styles__Container-sc-000000-0`. But it would be the same for the …
=> Add "meaninglessFileNames" option

.github/workflows/codeql-analysis.yml
According to warning:
```
This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
```
Need to bump CodeQL GH Action to the latest version.
=> bump codeql GH Action to v2

src/utils/detectors.js, src/utils/getSequenceExpressionValue.js, src/visitors/assignStyledRequired.js, test/fixtures/pre-transpiled/.babelrc, test/fixtures/pre-transpiled/code.js, test/fixtures/pre-transpiled/output.js
This adds support for identifying styled components imports using `_interopRequiredDefault` and calls to styled components that use sequence expressions (ex. `(0, _styled)('div')()`).
This should improve support for MUI + Next with SSR.
In `isStyled`, I added equivalent checks for sequence expressions wherever they could be used instead of member expressions. However, there's one case that I'm not sure will ever apply:
```js
(importLocalName('default', state) &&
t.isCallExpression(tag) &&
t.isMemberExpression(tag.callee) &&
tag.object.property.name === 'default' &&
tag.object.object.name === importLocalName('default', state))
```
Please let me know if this needs an equivalent sequence expression check.
I thought maybe this PR might add some new errors on re-transpilation, but I ran tests …
=> Support pre-transpiled code (#379)

package.json, yarn.lock
Hi! 👋
This PR updates the version of lodash to fix https://github.com/advisories/GHSA-p6mc-m468-83gw.
The tests seem to pass, let me know if you need anything else!
=> updated lodash from 4.17.11 to 4.17.21

src/visitors/assignStyledRequired.js
Prior to this change, code with template literals inside of `require` calls would break. This is because the check of `t.isLiteral` is far too broad for this usage, and assumes that all literals have a `value` property. Since `TemplateLiteral` nodes do not, they would cause `picomatch` to fail on an `undefined` input.
=> When testing import paths, only use string literals.
